services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=vacancies
      - DB_USER=postgres
      - DB_PASSWORD=ahb837js
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: vacancies
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ahb837js
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: